version: '3'
services:
  webserver:
    image: 
      nginx:alpine
    container_name: webserver
    restart: always
    tty: 
      true
    ports:
      - "80:80"
    networks:
      - net
    volumes:
      - ../frontend:/usr/share/nginx/html

  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - ../pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  pgmyadmin:
    image: 
      dpage/pgadmin4 
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: PaSsWoRd21
      PGADMIN_DEFAULT_EMAIL: mail@mail.ru
    networks:
      net:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: $NETWORK