CREATE TABLE IF NOT EXISTS "user"
(id SERIAL NOT NULL PRIMARY KEY,
email VARCHAR(320) NOT NULL,
hashpass VARCHAR(160) NOT NULL);

CREATE TABLE IF NOT EXISTS "session"
(session_id VARCHAR(128) NOT NULL,
user_id INT NOT NULL,
expires BIGINT NOT NULL);
	
CREATE TABLE IF NOT EXISTS "group"
(id SERIAL NOT NULL PRIMARY KEY,
user_id INT,
status_id INT NOT NULL,
width FLOAT,
length FLOAT);

CREATE TABLE IF NOT EXISTS robot
(id SERIAL NOT NULL PRIMARY KEY,
group_id INT,
user_id INT,
type_id INT NOT NULL,
token VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS robot_type
(id SERIAL NOT NULL PRIMARY KEY,
name VARCHAR(24));